Add application
fintarin/Fintamath-Android pull request #8
Opened 2022-03-22 23:15 UTC by Anonimprogramer

2022-03-22 23:43 UTC, fintarin requested changes

2022-03-22 23:43 UTC, fintarin commented on app/build.gradle
> +        applicationId "com.fintarin.fintamath_android"
fintamath

2022-03-22 23:43 UTC, fintarin commented on app/src/androidTest/java/com/fintarin/fintamath_android/ExampleInstrumentedTest.kt
> +package com.fintarin.fintamath_android
com.fintarin.fintamath

2022-03-22 23:43 UTC, fintarin commented on app/src/main/AndroidManifest.xml
> +    package="com.fintarin.fintamath_android">
com.fintarin.fintamath

2022-03-22 23:43 UTC, fintarin commented on app/src/main/AndroidManifest.xml
> +        android:theme="@style/Theme.Fintamathandroid">
Theme.Fintamath

2022-03-22 23:43 UTC, fintarin commented on app/src/main/AndroidManifest.xml
> +            android:name="com.fintarin.fintamath_android.MainActivity"
com.fintarin.fintamath

2022-03-22 23:43 UTC, fintarin commented on lib/src/FintamathLib.cpp
>  #include "fintamath/solver/Solver.hpp"
Format

2022-05-15 23:00 UTC, artrayme commented
не лезь...

2022-09-13 14:23 UTC, merged

2022-09-13 15:08 UTC, artrayme commented
гг